# Generated by Django 3.2.7 on 2021-10-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recive_job_applications',
            name='job_created_by',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
