# Generated by Django 3.2.7 on 2021-10-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_recive_job_applications_job_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
