# Generated by Django 3.2.7 on 2021-10-20 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_job_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='created_by',
        ),
    ]
