# Generated by Django 3.2.7 on 2021-10-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_job_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recive_job_applications',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
